#ifndef GFX_SCREEN_CONFIG_H
#define GFX_SCREEN_CONFIG_H

#ifdef __SWITCH
#define DESIRED_SCREEN_WIDTH 1280
#define DESIRED_SCREEN_HEIGHT 720
#else
#define DESIRED_SCREEN_WIDTH 640
#define DESIRED_SCREEN_HEIGHT 480
#endif

#endif
